### PR TITLE
Convert into es6 module

### PR DESCRIPTION
**Pull request by paxperscientiam**
Hi @badzong , here we have my attempt to es6-ify your code. 

* Introduce build process using `FuseBox`
* Allow user to instantiate class with desired property values.
* "dist" version will work out of the box
* "src" version was designed with fusebox in mind. 

I haven't tried building with `uglify-js` alone. In fact, I think it needs `uglify-es`. 

If you like where this is going, would you test building with Uglify-es and/or webpack?

Consider checking out the build scripts! `yarn start` and `yarn build`

Peace

### CODE REVIEW

**Comment by badzong** [comment]
Thank you for the improvements and the packaging. The Makefile seems a bit lost now. I'll check out the build scripts later today and maybe remove the Makefile completely.

Could you also add a short description of your build routine to the README.md?

**Comment by paxperscientiam** [comment]
You're welcome. Did you test? :P 

Yeah, I can write up a bit (maybe later today).

Glad you are happy with it.

**Comment by badzong** [comment]
Just tested it. Looks good to me :)

**Comment by paxperscientiam** [comment]
Last thing, should this commit be deployed as new release?

EDIT: @badzong, actually don't tag this: see #5 for why.

**Pull request merged**
